# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bug1.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1158, 837)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.submit_frame = QtWidgets.QFrame(self.centralwidget)
        self.submit_frame.setGeometry(QtCore.QRect(30, 30, 651, 361))
        self.submit_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.submit_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.submit_frame.setObjectName("submit_frame")
        self.submit_title_label = QtWidgets.QLabel(self.submit_frame)
        self.submit_title_label.setGeometry(QtCore.QRect(30, 10, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.submit_title_label.setFont(font)
        self.submit_title_label.setObjectName("submit_title_label")
        self.submit_table = QtWidgets.QTableWidget(self.submit_frame)
        self.submit_table.setGeometry(QtCore.QRect(20, 50, 463, 179))
        self.submit_table.setObjectName("submit_table")
        self.submit_table.setColumnCount(5)
        self.submit_table.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.submit_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.submit_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.submit_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.submit_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(255, 170, 0))
        self.submit_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(255, 170, 0))
        self.submit_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(255, 170, 0))
        self.submit_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(255, 170, 0))
        self.submit_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(255, 170, 0))
        self.submit_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.submit_table.setItem(0, 0, item)
        self.submit_table.horizontalHeader().setCascadingSectionResizes(False)
        self.submit_table.horizontalHeader().setDefaultSectionSize(80)
        self.submit_table.horizontalHeader().setMinimumSectionSize(29)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1158, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.submit_title_label.setText(_translate("MainWindow", "本周提交BUG"))
        item = self.submit_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Bloker"))
        item = self.submit_table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Critical"))
        item = self.submit_table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Major"))
        item = self.submit_table.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Minor"))
        item = self.submit_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "AND"))
        item = self.submit_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "IOS"))
        item = self.submit_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "H5"))
        item = self.submit_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "SER"))
        item = self.submit_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "PRO"))
        __sortingEnabled = self.submit_table.isSortingEnabled()
        self.submit_table.setSortingEnabled(False)
        self.submit_table.setSortingEnabled(__sortingEnabled)

